# Generated by Django 4.1.7 on 2023-06-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='admin_ID',
        ),
    ]
