<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-06-02 02:58
=======
# Generated by Django 4.1.7 on 2023-05-03 16:04
# Generated by Django 4.1.7 on 2023-04-07 08:05
>>>>>>> 4d935eb6523befaa5a3f3f5db8a74af94f22d345

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True, max_length=20)),
            ],
        ),
    ]
