# Generated by Django 4.1.7 on 2023-06-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='admin_ID',
        ),
    ]
