# Generated by Django 4.1.7 on 2023-03-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('Auth', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='adminservice_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dep_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.department'),
        ),
    ]
