# Generated by Django 4.1.7 on 2023-03-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='admin_service_ID',
            new_name='adminservice_ID',
        ),
    ]
