# Generated by Django 4.1.7 on 2023-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_status_appointment_approvalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ApprovalStatus',
            field=models.CharField(default='pending', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_ID',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
