# Generated by Django 4.1.7 on 2023-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
