# Generated by Django 4.1.7 on 2023-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_name_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
