# Generated by Django 4.1.7 on 2023-06-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
