# Generated by Django 4.1.7 on 2023-06-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidCatagory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catagoryName', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Commpetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_id', models.IntegerField(null=True)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('final_price', models.FloatField()),
                ('customer_ID', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('initial_price', models.FloatField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('catagory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bid.bidcatagory')),
            ],
        ),
    ]
