# Generated by Django 4.1.7 on 2023-04-07 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidCatagory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catagoryName', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BidInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=39)),
                ('description', models.TextField(max_length=200)),
                ('initial_price', models.FloatField()),
                ('end_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('winner', models.TextField(max_length=20)),
                ('final_price', models.FloatField()),
                ('numberOfExperience', models.IntegerField()),
                ('catagory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bid.bidcatagory')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_Id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('numberOfExperience', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('bidInfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bid.bidinfo')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcreator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
