# Generated by Django 4.1.7 on 2023-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0003_remove_bidinfo_end_time_remove_bidinfo_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidinfo',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
