# Generated by Django 4.1.7 on 2023-04-07 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bid', '0004_bidinfo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commpetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('final_price', models.FloatField()),
                ('winner', models.TextField(max_length=20)),
                ('numberOfExperience', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='initial_price',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='numberOfExperience',
            new_name='minimum_numberOfExperience',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidInfo_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='catagory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bid.bidcatagory'),
        ),
        migrations.AddField(
            model_name='bid',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='BidInfo',
        ),
        migrations.AddField(
            model_name='commpetition',
            name='bid_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bid.bid'),
        ),
        migrations.AddField(
            model_name='commpetition',
            name='winner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_Id', to=settings.AUTH_USER_MODEL),
        ),
    ]
